#CC=g++
#CFLAGS=-pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm -std=c++11
#
#all: da1
#
#da1: main.o vector.o
#	$(CC) main.o vector.o -o da1
#
#main.o: main.cpp
#	$(CC) $(CFLAGS) main.cpp
#
#vector.o: Vector.cpp
#	$(CC) $(CFLAGS) Vector.cpp

#clean:
#	rm -rf *.o da1

all:
	g++ -g -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm -std=c++11 main.cpp TVector.cpp -o da1